### ISSUE TITLE
Not compatible WorldGuard 7

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#11]
Please make this plugin compatible WorldGuard 7

**Comment by utarwyn** [comment]
Yes, I never have already working on that version of WorldGuard for EnderContainers.
Where I can download it? Or perhaps a Maven repository with it?

Thank you for this suggestion. 👍

**Comment by andris155** [comment]
http://builds.enginehub.org/job/worldguard?branch=string-ids

**Comment by sinni1997** [comment]
Do you made it compatible with WorldGuard 7 already? 
Your plugin is exactly what i needed but users always get this error when they try to open the enderchest:
[18:44:32 ERROR]: Could not pass event PlayerInteractEvent to EnderContainers v2.1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1201) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(SourceFile:53) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(SourceFile:11) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839) [craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at fr.utarwyn.endercontainers.dependencies.WorldGuardDependency.onBlockChestOpened(WorldGuardDependency.java:37) ~[?:?]
        at fr.utarwyn.endercontainers.dependencies.DependenciesManager.onBlockChestOpened(DependenciesManager.java:165) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChestListener.onPlayerInteract(EnderChestListener.java:71) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WGBukkit
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at fr.utarwyn.endercontainers.dependencies.WorldGuardDependency.onBlockChestOpened(WorldGuardDependency.java:37) ~[?:?]
        at fr.utarwyn.endercontainers.dependencies.DependenciesManager.onBlockChestOpened(DependenciesManager.java:165) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChestListener.onPlayerInteract(EnderChestListener.java:71) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[craftbukkit-1.13.2.jar:git-Bukkit-a2dd0e3]
        ... 17 more

Oped players can regularly open it.

**Comment by utarwyn** [comment]
The bug is still here... because I have not worked on it until now.
I hope to fix it very soon. Thank you for the feedback.

**Comment by utarwyn** [comment]
Thanks to a recent fix, EnderContainers is now fully compatible with WorldGuard 6+ and 7+.
All changes are in this commit: feedda7e841e47d3e1c4d52e6f90a3addd25fe80

Does it work for you now? If it's good, can you close this issue?

Thanks in advance.

**Comment by andris155** [comment]
Works, thanks!
