### ISSUE TITLE
Plugin start error Paper 1.13

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#14]
```
[17:10:05] [Server thread/INFO]: [EnderContainers] Enabling EnderContainers v2.1.0
[17:10:05] [Server thread/INFO]: [EnderContainers] -----------[Dependencies]-----------
[17:10:05] [Server thread/INFO]: [EnderContainers]   Use Citizens (v2.0.23-SNAPSHOT (build 1564)) as a dependency!
[17:10:05] [Server thread/WARN]: [EnderContainers] Cannot unregister the command enderchest from the server!
java.lang.NoSuchFieldException: knownCommands
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_171]
	at fr.utarwyn.endercontainers.commands.AbstractCommand.unregister(AbstractCommand.java:343) ~[?:?]
	at fr.utarwyn.endercontainers.dependencies.EssentialsDependency.onEnable(EssentialsDependency.java:29) ~[?:?]
	at fr.utarwyn.endercontainers.dependencies.DependenciesManager.registerDependency(DependenciesManager.java:121) ~[?:?]
	at fr.utarwyn.endercontainers.dependencies.DependenciesManager.loadDependencies(DependenciesManager.java:105) ~[?:?]
	at fr.utarwyn.endercontainers.dependencies.DependenciesManager.initialize(DependenciesManager.java:50) ~[?:?]
	at fr.utarwyn.endercontainers.AbstractManager.<init>(AbstractManager.java:40) ~[?:?]
	at fr.utarwyn.endercontainers.dependencies.DependenciesManager.<init>(DependenciesManager.java:38) ~[?:?]
	at fr.utarwyn.endercontainers.EnderContainers.onEnable(EnderContainers.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-173]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[17:10:05] [Server thread/INFO]: [EnderContainers]   Use Essentials (v2.15.0.45) as a dependency!
[17:10:05] [Server thread/INFO]: [EnderContainers]   2 dependencies loaded!
[17:10:05] [Server thread/INFO]: [EnderContainers] ------------------------------------
[17:10:05] [Server thread/INFO]: [EnderContainers] MySQL disabled. Use flat system to store data.
```

**Comment by utarwyn** [comment]
Oh my bad, I did not know that this field was removed by Paper on 1.13 versions! 😞 
I will fix that now

**Comment by utarwyn** [comment]
This error should no longer appear thanks to the last commit I made

**Comment by utarwyn** [comment]
This error should no longer appears thank to the last commit I made (here: https://github.com/utarwyn/EnderContainers/commit/c78431680524a1597018559508fc4dde566b0e75)

Is it good for you? Sorry for the inconvenience.

**Comment by andris155** [comment]
Works perfectly
