### ISSUE TITLE
1.18 Update please.

### ISSUE THREAD

**Issue by andy3559167** [utarwyn/EnderContainers#183]
server : paper-1.18-27   EnderContainers-2.3.0-SNAPSHOT.jar(#13)

[02:23:29 WARN]: [EnderContainers] Plugin EnderContainers v2.3.0-dev generated an exception while executing task 4
java.lang.NullPointerException: Cannot invoke "fr.utarwyn.endercontainers.compatibility.ServerVersion.ordinal()" because the return value of "fr.utarwyn.endercontainers.compatibility.ServerVersion.get()" is null
        at fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:54) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.configuration.Locale.formatMessage(Locale.java:120) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.configuration.Locale.lambda$getMessage$0(Locale.java:90) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at fr.utarwyn.endercontainers.configuration.Locale.getMessage(Locale.java:89) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.getTitle(EnderChestInventory.java:110) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.AbstractInventoryHolder.reloadInventory(AbstractInventoryHolder.java:116) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.<init>(EnderChestInventory.java:46) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.updateContainer(EnderChest.java:245) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:54) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.createEnderchest(PlayerContext.java:209) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.loadEnderchests(PlayerContext.java:121) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.LoadTask.run(LoadTask.java:64) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-27]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-27]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-27]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by utarwyn** [comment]
Yes indeed.. I will work on that!

**Comment by andy3559167** [comment]
Your plugin is easy to use, thank you for your development<3
