### ISSUE TITLE
Fatal error and server crash

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#19]
```
[01:16:50] [Craft Scheduler Thread - 91/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 233280
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.util.ArrayList.add(ArrayList.java:486) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:498) ~[?:?]
	at net.minecraft.server.v1_13_R2.InventoryCrafting.onOpen(InventoryCrafting.java:33) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:39) ~[patched_1.13.2.jar:git-Paper-500]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1187) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.EntityPlayer.closeInventory(EntityPlayer.java:1031) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.EntityPlayer.openContainer(EntityPlayer.java:896) ~[patched_1.13.2.jar:git-Paper-500]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:306) ~[patched_1.13.2.jar:git-Paper-500]
	at fr.utarwyn.endercontainers.menu.AbstractMenu.open(AbstractMenu.java:91) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:115) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:125) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestListener.lambda$onPlayerInteract$0(EnderChestListener.java:77) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-500]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-500]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-500]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:16:50] [Craft Scheduler Thread - 119/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 233277
net.minecraft.server.v1_13_R2.CancelledPacketHandleException: null
[01:16:50] [Craft Scheduler Thread - 118/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 233278
net.minecraft.server.v1_13_R2.CancelledPacketHandleException: null
[01:16:50] [Craft Scheduler Thread - 123/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 233276
net.minecraft.server.v1_13_R2.CancelledPacketHandleException: null
[01:16:50] [Server thread/FATAL]: Error executing task
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.util.ArrayList.add(ArrayList.java:486) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:498) ~[?:?]
	at net.minecraft.server.v1_13_R2.InventoryCrafting.onOpen(InventoryCrafting.java:33) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.Container.transferTo(Container.java:39) ~[patched_1.13.2.jar:git-Paper-500]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1187) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2080) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-500]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-500]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-500]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by andris155** [comment]
This cause multiple open enderchest on server lag.

**Comment by andris155** [comment]
I removed async openHubMenuFor and fixed this bug.

**Comment by utarwyn** [comment]
Okay, thank you for the feedback! 👍 
I will see to fix some performance issues with async tasks of the plugin.
