### ISSUE TITLE
Version 2.2.2 unable to open enderchest

### ISSUE THREAD

**Issue by EntityStrike** [utarwyn/EnderContainers#198]
EnderContainers version: 2.2.2
Platform version: Win11 - Server is on Paper 1.18.1

**Describe the bug**
The ender chest does not make a noise and doesn't open either. Using /ecp open {player} doesn't work as no response is given when looking through the console.

**To Reproduce**

1. Boot up your server on Paper 1.18.1
2. (Nothing else)

**Expected behavior**
I expected for the chest to open, it didn't.

**Screenshots**
N/A

**Additional context**
Probably 2.2.2 doesn't support 1.18.1, but just wanted to let you know anyways.
(It was working on 1.18.1 just yesterday, but stopped working today even though I haven't edited anything.)

Closest Error I could find in the logs are these, however I'm not sure if it is related.

```
[16:41:39 WARN]: [EnderContainers] Plugin EnderContainers v2.2.2 generated an exception while executing task 303
java.lang.NullPointerException: Cannot invoke "fr.utarwyn.endercontainers.compatibility.ServerVersion.ordinal()" because the return value of "fr.utarwyn.endercontainers.compatibility.ServerVersion.get()" is null
	at fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:54) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.configuration.Locale.formatMessage(Locale.java:70) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.configuration.Locale.lambda$getMessage$0(Locale.java:58) ~[Endercontainers-2.2.2.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at fr.utarwyn.endercontainers.configuration.Locale.getMessage(Locale.java:57) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.inventory.EnderChestInventory.getTitle(EnderChestInventory.java:109) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.inventory.AbstractInventoryHolder.reloadInventory(AbstractInventoryHolder.java:116) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.inventory.EnderChestInventory.<init>(EnderChestInventory.java:45) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:49) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.createEnderchest(PlayerContext.java:207) ~[Endercontainers-2.2.2.jar:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.loadEnderchests(PlayerContext.java:122) ~[Endercontainers-2.2.2.jar:?]
	at fr.utarwyn.endercontainers.enderchest.context.LoadTask.run(LoadTask.java:63) ~[Endercontainers-2.2.2.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-207]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-207]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by utarwyn** [comment]
Hello, version **2.2.2** of EnderContainers does not work with Minecraft 1.18. But the version **2.2.3** which has not been uploaded to SpigotMC should work. You can download it from my integration service: https://ci.utarwyn.fr/job/EnderContainers/.

But yeah I think it's a good idea to fisplay a more comprehensive error message when the version is not supported by the plugin.
