### ISSUE TITLE
1.9.4 spigot

### ISSUE THREAD

**Issue by koptokop** [utarwyn/EnderContainers#20]
[12:56:33] [Craft Scheduler Thread - 201/WARN]: Exception in thread "Craft Scheduler Thread - 201" 
[12:56:33] [Craft Scheduler Thread - 201/WARN]: org.apache.commons.lang.UnhandledException: Plugin EnderContainers v2.1.0 generated an exception while executing task 718088
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.minecraft.server.v1_9_R2.CancelledPacketHandleException

[12:56:37] [Craft Scheduler Thread - 199/WARN]: Exception in thread "Craft Scheduler Thread - 199" 
[12:56:37] [Craft Scheduler Thread - 199/WARN]: org.apache.commons.lang.UnhandledException: Plugin EnderContainers v2.1.0 generated an exception while executing task 718667
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.minecraft.server.v1_9_R2.CancelledPacketHandleException

**Comment by utarwyn** [comment]
Hello @koptokop,

What a strange error... When does it occur? Is it often?

I think this is due to an error during an asynchrone task in the plugin.
I have to work about that to make errors clearer.

Regards.

**Comment by koptokop** [comment]
log
[latest.log](https://github.com/utarwyn/EnderContainers/files/3186532/latest.log)

**Comment by koptokop** [comment]
@utarwyn
[latest.log](https://github.com/utarwyn/EnderContainers/files/3186540/latest.log)

**Comment by utarwyn** [comment]
Related to #24.
I should rework on thread management across all the plugin to optimise it and avoid exceptions like this.
