### ISSUE TITLE
Update 1.19 please.

### ISSUE THREAD

**Issue by andy3559167** [utarwyn/EnderContainers#202]
[02:38:23] [Craft Scheduler Thread - 0/WARN]: [EnderContainers] Plugin EnderContainers v2.2.3-dev generated an exception while executing task 17
java.lang.NullPointerException: Cannot invoke "fr.utarwyn.endercontainers.compatibility.ServerVersion.ordinal()" because the return value of "fr.utarwyn.endercontainers.compatibility.ServerVersion.get()" is null
        at fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:55) ~[?:?]
        at fr.utarwyn.endercontainers.configuration.Locale.formatMessage(Locale.java:70) ~[?:?]
        at fr.utarwyn.endercontainers.configuration.Locale.lambda$getMessage$0(Locale.java:58) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at fr.utarwyn.endercontainers.configuration.Locale.getMessage(Locale.java:57) ~[?:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.getTitle(EnderChestInventory.java:109) ~[?:?]
        at fr.utarwyn.endercontainers.inventory.AbstractInventoryHolder.reloadInventory(AbstractInventoryHolder.java:116) ~[?:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.<init>(EnderChestInventory.java:45) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.updateContainer(EnderChest.java:229) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:49) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.createEnderchest(PlayerContext.java:207) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.loadEnderchests(PlayerContext.java:122) ~[?:?]
        at fr.utarwyn.endercontainers.enderchest.context.LoadTask.run(LoadTask.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by utarwyn** [comment]
Hello @andy3559167, support for **Minecraft 1.19** has been added to the plugin! **(v2.2.3 and v2.3.0)**
There were not many changes to make as this is not a very structural update.

You can download builds here: https://github.com/utarwyn/EnderContainers#downloads

**Comment by andy3559167** [comment]
thanks you!! <3
