### ISSUE TITLE
Open enderchest claim factionuuid

### ISSUE THREAD

**Issue by omgloer** [utarwyn/EnderContainers#205]
Hello, I have an error when I try to open the enderchest in a claim

```
Could not pass event PlayerInteractEvent to EnderContainers v2.2.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[Spigot.jar:]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Spigot.jar:]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[Spigot.jar:]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[Spigot.jar:]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[Spigot.jar:]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:321) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:465) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1002) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:74) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[Spigot.jar:]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[Spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[Spigot.jar:]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/zcore/fperms/PermissableAction
at fr.utarwyn.endercontainers.dependency.Factions1Dependency.validateBlockChestOpening(Factions1Dependency.java:52) ~[?:?]
at fr.utarwyn.endercontainers.dependency.DependenciesManager.validateBlockChestOpening(DependenciesManager.java:74) ~[?:?]
at fr.utarwyn.endercontainers.enderchest.EnderChestListener.onPlayerInteract(EnderChestListener.java:81) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor241.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[Spigot.jar:]
... 18 more 
```

**Comment by utarwyn** [comment]
Hello! Which version/plugin of Factions do you use?

**Comment by omgloer** [comment]
I use FactionsUUID 1.6.9.5-U0.6.12-b290

**Comment by utarwyn** [comment]
This version **is not well supported in the latest stable version of the plugin**, sorry for that..
The creator of this updated version of Factions has opened another issue about it, check it here: #182.

So, I have already worked in #189 on it to solve the issue. The fix will be available from version 2.2.3 of the plugin.
If needed, you can download developments builds from GitHub: https://github.com/utarwyn/EnderContainers#downloads
