### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by andy3559167** [utarwyn/EnderContainers#240]
[01:16:54 INFO]: andy_1203 issued server command: /ec
[01:16:54 WARN]: [EnderContainers] Plugin EnderContainers v2.3.0-dev generated an exception while executing task 5304
java.lang.NullPointerException: Cannot invoke "fr.utarwyn.endercontainers.compatibility.ServerVersion.ordinal()" because the return value of "fr.utarwyn.endercontainers.compatibility.ServerVersion.get()" is null
        at fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:58) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.configuration.Locale.formatMessage(Locale.java:120) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.configuration.Locale.lambda$getMessage$0(Locale.java:90) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at fr.utarwyn.endercontainers.configuration.Locale.getMessage(Locale.java:89) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.getTitle(EnderChestInventory.java:110) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.AbstractInventoryHolder.reloadInventory(AbstractInventoryHolder.java:116) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.inventory.EnderChestInventory.<init>(EnderChestInventory.java:46) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.updateContainer(EnderChest.java:245) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:54) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.createEnderchest(PlayerContext.java:209) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.PlayerContext.loadEnderchests(PlayerContext.java:121) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at fr.utarwyn.endercontainers.enderchest.context.LoadTask.run(LoadTask.java:64) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.jar:git-Purpur-1986]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.jar:git-Purpur-1986]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by utarwyn** [comment]
Thank you for the issue! It reminds me each time to add support for the newer version of Minecraft :+1:
