### ISSUE TITLE
Minecraft 1.20.x and 1.21 support

### ISSUE THREAD

**Issue by ava852546** [utarwyn/EnderContainers#268]
EnderContainers-2.3.0-SNAPSHOT
Current Purpur Version: 1.20.6-2224-be3a6d5 (MC: 1.20.6)*
* You are running the latest version

"/ec" not working

**Comment by Sylensky** [comment]
I can bring some light into this issue and share some logs as the plugin is also not working on my side.
Server version: Paper version 1.20.6-147-ver/1.20.6@e41d44f

```
2024-07-01T21:06:32.456259653Z > 
[22:06:32 WARN]: [EnderContainers] Plugin EnderContainers v2.3.0-dev generated an exception while executing task 59480
2024-07-01T21:06:32.456279697Z java.lang.NullPointerException: Cannot invoke "fr.utarwyn.endercontainers.compatibility.ServerVersion.ordinal()" because the return value of "fr.utarwyn.endercontainers.compatibility.ServerVersion.get()" is null
2024-07-01T21:06:32.456295853Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:59) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456299850Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.configuration.Locale.formatMessage(Locale.java:120) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456303154Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.configuration.Locale.lambda$getMessage$0(Locale.java:90) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456306617Z 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
2024-07-01T21:06:32.456309760Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.configuration.Locale.getMessage(Locale.java:89) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456317461Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.inventory.EnderChestInventory.getTitle(EnderChestInventory.java:110) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456321180Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.inventory.AbstractInventoryHolder.reloadInventory(AbstractInventoryHolder.java:116) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456324475Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.inventory.EnderChestInventory.<init>(EnderChestInventory.java:46) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456327766Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.enderchest.EnderChest.updateContainer(EnderChest.java:245) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456331028Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:54) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456335367Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.enderchest.context.PlayerContext.createEnderchest(PlayerContext.java:209) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456338704Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.enderchest.context.PlayerContext.loadEnderchests(PlayerContext.java:121) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456341869Z 	at EnderContainers-2.3.0-SNAPSHOT.jar/fr.utarwyn.endercontainers.enderchest.context.LoadTask.run(LoadTask.java:64) ~[EnderContainers-2.3.0-SNAPSHOT.jar:?]
2024-07-01T21:06:32.456345020Z 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
2024-07-01T21:06:32.456348089Z 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
2024-07-01T21:06:32.456350992Z 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
2024-07-01T21:06:32.456353862Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
2024-07-01T21:06:32.456356869Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
2024-07-01T21:06:32.456359947Z 	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by utarwyn** [comment]
Hello, thank you for the feedback. 👍 The plugin doesn't support Minecraft 1.20.3+ and 1.21 yet.
I'm waiting for the first 1.21 Paper stable build to get things moving!

**Comment by Sylensky** [comment]
Your friendly reminder that stable paper builds are available since 20.7. arrived ;)
