### ISSUE TITLE
Please optimise plugin

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#3]
![annotation](https://user-images.githubusercontent.com/8324198/42137751-65fa1b28-7d72-11e8-80b1-e3bbed9a1296.png)

**Comment by utarwyn** [comment]
Hello @andris155,
that's a strange behavior, but that is possible.

I need more information to try to optimize the plugin:
- Are you running the latest version of the plugin?
- Has your server been running without a restart for a long time?
- Have you any error in the console?

Thank you in advance.

**Comment by andris155** [comment]
Plugin version: 2.1.0
My server restart every 24 hours.

```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_171]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_171]
	at fr.utarwyn.endercontainers.menu.Menus.getMenuFromInventory(Menus.java:91) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.menu.Menus.onInventoryClick(Menus.java:58) ~[EnderContainers-2.1.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor929.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
	... 16 more
```

**Comment by andris155** [comment]
```
[13:14:19] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to EnderContainers v2.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:932) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1761) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:777) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:829) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) ~[patched_1.12.2.jar:git-Paper-1468]
	at hu.infinityhosting.bukkit.managers.GUIManager.onProductsInventory(GUIManager.java:206) ~[MineMarket-Universal.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor256.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_171]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_171]
	at fr.utarwyn.endercontainers.menu.Menus.getMenuFromInventory(Menus.java:91) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.menu.Menus.onInventoryClose(Menus.java:77) ~[EnderContainers-2.1.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor930.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
	... 28 more
```

**Comment by utarwyn** [comment]
It might exists a memory problem with menus, I will look into that to improve the plugin. I will fix that error by the same time.

**Comment by utarwyn** [comment]
476829747d20e84544fdbde182536e173e78503e

**Comment by andris155** [comment]
Plugin version: 2.1.0
Server: Paper 1.12.2
New errors
```
[14:26:07] [Server thread/INFO]: MatiasX issued server command: /ecp open asdlol911
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:356)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:352)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.q(World.java:1444)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.getSpawnPoint(EntityPlayer.java:136)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.<init>(EntityPlayer.java:101)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.NMSHacks.getPlayerObjectOfOfflinePlayer(NMSHacks.java:77)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.EUtil.getVanillaEnderchestOf(EUtil.java:122)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestMenu.getFilledSlotsNb(EnderChestMenu.java:60)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChest.getFillPercentage(EnderChest.java:105)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.getItemStackOf(EnderChestHubMenu.java:101)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.prepare(EnderChestHubMenu.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:113)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.commands.EnderContainersCommand.lambda$onCommand$0(EnderContainersCommand.java:116)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:356)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:352)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.q(World.java:1444)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.getSpawnPoint(EntityPlayer.java:136)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.<init>(EntityPlayer.java:101)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.NMSHacks.getPlayerObjectOfOfflinePlayer(NMSHacks.java:77)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.EUtil.getVanillaEnderchestOf(EUtil.java:122)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestMenu.getFilledSlotsNb(EnderChestMenu.java:60)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChest.getSize(EnderChest.java:81)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.getItemStackOf(EnderChestHubMenu.java:112)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.prepare(EnderChestHubMenu.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:113)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.commands.EnderContainersCommand.lambda$onCommand$0(EnderContainersCommand.java:116)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:356)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:352)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.World.q(World.java:1444)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.getSpawnPoint(EntityPlayer.java:136)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.<init>(EntityPlayer.java:101)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.NMSHacks.getPlayerObjectOfOfflinePlayer(NMSHacks.java:77)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.util.EUtil.getVanillaEnderchestOf(EUtil.java:122)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestMenu.getFilledSlotsNb(EnderChestMenu.java:60)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChest.getSize(EnderChest.java:81)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChest.isFull(EnderChest.java:137)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.getItemStackOf(EnderChestHubMenu.java:125)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.prepare(EnderChestHubMenu.java:62)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:113)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at fr.utarwyn.endercontainers.commands.EnderContainersCommand.lambda$onCommand$0(EnderContainersCommand.java:116)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:26:07] [Craft Scheduler Thread - 1480/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

```
[17:11:57] [Craft Scheduler Thread - 1990/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 1451815
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.fastRemove(ArrayList.java:550) ~[?:1.8.0_171]
	at java.util.ArrayList.remove(ArrayList.java:533) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.PlayerInventory.onClose(PlayerInventory.java:50) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.Container.transferTo(Container.java:39) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:782) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:829) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) ~[patched_1.12.2.jar:git-Paper-1468]
	at fr.utarwyn.endercontainers.menu.AbstractMenu.open(AbstractMenu.java:91) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:114) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:124) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestListener.lambda$onPlayerInteract$0(EnderChestListener.java:75) ~[EnderContainers-2.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1468]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

```
[20:15:19] [Craft Scheduler Thread - 2619/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 1958133
java.lang.NullPointerException: null
	at fr.utarwyn.endercontainers.storage.player.PlayerFlatData.getEnderchestContents(PlayerFlatData.java:38) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChest.load(EnderChest.java:224) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChest.<init>(EnderChest.java:57) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.getEnderChest(EnderChestManager.java:78) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.prepare(EnderChestHubMenu.java:55) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:113) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:124) ~[EnderContainers-2.1.0.jar:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestListener.lambda$onPlayerInteract$0(EnderChestListener.java:75) ~[EnderContainers-2.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1468]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by andris155** [comment]
```
[13:16:12] [Craft Scheduler Thread - 799/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 601673
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_171]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_171]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.getEnderChest(EnderChestManager.java:75) ~[?:?]
	at fr.utarwyn.endercontainers.menu.EnderChestHubMenu.prepare(EnderChestHubMenu.java:95) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:114) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestManager.openHubMenuFor(EnderChestManager.java:125) ~[?:?]
	at fr.utarwyn.endercontainers.enderchest.EnderChestListener.lambda$0(EnderChestListener.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1517]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1517]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1517]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by andris155** [comment]
```
[14:43:11] [Craft Scheduler Thread - 963/WARN]: [EnderContainers] Plugin EnderContainers v2.1.0 generated an exception while executing task 812492
net.minecraft.server.v1_12_R1.CancelledPacketHandleException: null
```

**Comment by andris155** [comment]
I removed async tasks from plugin. This fixed all errors and warns.

**Comment by utarwyn** [comment]
Yep, thank you for the feedback. So the main problem seems to be async tasks.
So, I have to work on that! Issue #24 is related to that.

**Comment by andris155** [comment]
If this not fixed, please remove async from plugin.
