### ISSUE TITLE
Not compatible PlotSquared 4.399

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#30]
```
[03:59:13] [Server thread/INFO]: [EnderContainers] Enabling EnderContainers v2.1.0
[03:59:13] [Server thread/ERROR]: Error occurred while enabling EnderContainers v2.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/github/intellectualsites/plotsquared/plot/flag/PlotBlockListFlag
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?]
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?]
	at java.lang.Class.newInstance(Unknown Source) ~[?:?]
	at fr.utarwyn.endercontainers.dependency.DependenciesManager.loadDependencies(DependenciesManager.java:95) ~[?:?]
	at fr.utarwyn.endercontainers.dependency.DependenciesManager.load(DependenciesManager.java:42) ~[?:?]
	at fr.utarwyn.endercontainers.Managers.register(Managers.java:52) ~[?:?]
	at fr.utarwyn.endercontainers.EnderContainers.onEnable(EnderContainers.java:69) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-226]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.plot.flag.PlotBlockListFlag
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-226]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 17 more
```

**Comment by utarwyn** [comment]
I don't understand why my plugin is trying to load the **PlotSquared** class `com/github/intellectualsites/plotsquared/plot/flag/PlotBlockListFlag` as it don't use it. I have to do some tests to identify more specifically the problem and try to resolve it.

**Comment by utarwyn** [comment]
Ok I just noticed that the author of PlotSquared has removed the class `PlotBlock` that I use to verify if enderchests are protected for usage in a zone. **I will update my plugin to support this modification**, but it will break the dependency for old versions of PlotSquared. Do you think necessary to support old versions as well?

**Comment by andris155** [comment]
I don't know why should support old versions.

**Comment by utarwyn** [comment]
I agree with you that I should not support old versions of PlotSquared.
So after some modifications on the code and few tests, I've made a commit to support PlotSquared 3.390+. Your can find it here: c9fd622a4274868a5ce55668e29d70291eb42106.

**Comment by andris155** [comment]
Works perfectly. Thanks.
