### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by B1gLev** [utarwyn/EnderContainers#73]
Version 1.15 when will you be in the githubos version?

[17:10:46] [Server thread/ERROR]: [EnderContainers] 
[17:10:46] [Server thread/ERROR]: [EnderContainers] >> --------------- <<
[17:10:46] [Server thread/ERROR]: [EnderContainers] >> CRITICAL ERROR! <<
[17:10:46] [Server thread/ERROR]: [EnderContainers] >> --------------- <<
[17:10:46] [Server thread/ERROR]: [EnderContainers] 
[17:10:46] [Server thread/ERROR]: [EnderContainers] >> Error when loading Yaml for class Locale! Yaml value COMMANDS.BACKUPS.CREATED cannot be parsed!
[17:10:46] [Server thread/ERROR]: [EnderContainers] >> Are you sure that value '&aBackup &b%backup%&a has been created.' is good?
[17:10:46] [Server thread/ERROR]: [EnderContainers] 
[17:10:46] [Server thread/ERROR]: [EnderContainers] Cannot parse the yaml file
java.lang.NullPointerException: null
	at fr.utarwyn.endercontainers.compatibility.ServerVersion.isOlderThan(ServerVersion.java:51) ~[EnderContainers-2.2.0.jar:?]
	at fr.utarwyn.endercontainers.configuration.Locale.parseValue(Locale.java:164) ~[EnderContainers-2.2.0.jar:?]
	at fr.utarwyn.endercontainers.configuration.YamlFile.load(YamlFile.java:60) [EnderContainers-2.2.0.jar:?]
	at fr.utarwyn.endercontainers.configuration.Files.initLocale(Files.java:72) [EnderContainers-2.2.0.jar:?]
	at fr.utarwyn.endercontainers.EnderContainers.onEnable(EnderContainers.java:63) [EnderContainers-2.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by utarwyn** [comment]
Hello @B1gLev, sorry about that problem. As the error comes from the class `ServerVersion`, it seems that the version of Minecraft that you are using is not supported by the plugin with the release that you have. The latest development version available should work from 1.8 to 1.15 versions of Minecraft.

:arrow_right: This build should solve your problem: [EnderContainers-2.2.0-9fc4ea2.zip](https://github.com/utarwyn/EnderContainers/files/4684171/EnderContainers-2.2.0-9fc4ea2.zip) *(development build)*
:information_source: The stable release **2.2.0** should be out everywhere fairly soon!

**Comment by B1gLev** [comment]
> Hello @B1gLev, sorry about that problem. As the error comes from the class `ServerVersion`, it seems that the version of Minecraft that you are using is not supported by the plugin with the release that you have. The latest development version available should work from 1.8 to 1.15 versions of Minecraft.
> 
>  This build should solve your problem: [EnderContainers-2.2.0-9fc4ea2.zip](https://github.com/utarwyn/EnderContainers/files/4684171/EnderContainers-2.2.0-9fc4ea2.zip) _(development build)_
>  The stable release **2.2.0** should be out everywhere fairly soon!

This is it! Thank you help and quick response!
